services:
  # ============================================
  # Production Service
  # Multi-stage build with Nginx
  # ============================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: scholarchains:latest
    container_name: scholarchains-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - scholarchains-network
    labels:
      - "com.scholarchains.service=production"
      - "com.scholarchains.version=1.0"

  # ============================================
  # Development Service
  # Vite dev server with HMR
  # ============================================
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: scholarchains:dev
    container_name: scholarchains-dev
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for live reload
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      # Exclude node_modules from volume mount (use container's)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=8080
      - VITE_API_URL=http://backend:3001
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - scholarchains-network
    labels:
      - "com.scholarchains.service=development"
      - "com.scholarchains.version=dev"

  # ============================================
  # Backend Service
  # OpenTimestamps API server
  # ============================================
  backend:
    build:
      context: ./scholarchains-backend
      dockerfile: Dockerfile
    image: scholarchains-backend:latest
    container_name: scholarchains-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
    restart: unless-stopped
    networks:
      - scholarchains-network
    labels:
      - "com.scholarchains.service=backend"
      - "com.scholarchains.version=1.0"

  # ============================================
  # Backend Development Service
  # Node.js with live reload
  # ============================================
  backend-dev:
    build:
      context: ./scholarchains-backend
      dockerfile: Dockerfile
      target: builder
    image: scholarchains-backend:dev
    container_name: scholarchains-backend-dev
    ports:
      - "3001:3001"
    volumes:
      - ./scholarchains-backend/src:/app/src:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
    command: npm run dev
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - scholarchains-network
    labels:
      - "com.scholarchains.service=backend-dev"
      - "com.scholarchains.version=dev"

networks:
  scholarchains-network:
    driver: bridge
    name: scholarchains-net
